name: docs_RingStates
channels:
  - conda-forge
  - defaults

dependencies:
    # Base depends
  - python
  - pip

    # Package depends
  - numpy
  - matplotlib

    # Pip-only installs
  - pip:
    - networkx
    - photonic_circuit_solver
    - qiskit
    - qiskit_aer